// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrPrjW0mu1TwvwNjeIz81-d90o299i8NA',
    appId: '1:606046467024:web:5fa23d4aeffb39562a7fd5',
    messagingSenderId: '606046467024',
    projectId: 'ellemora-7629c',
    authDomain: 'ellemora-7629c.firebaseapp.com',
    storageBucket: 'ellemora-7629c.appspot.com',
    measurementId: 'G-2BTZ0NCWXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHUZ4L59b3PN1FhlYZbApJzKHBK0dS2zU',
    appId: '1:606046467024:android:9b7e6a3771d03b5d2a7fd5',
    messagingSenderId: '606046467024',
    projectId: 'ellemora-7629c',
    storageBucket: 'ellemora-7629c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc1OVJRns3lTpiMqr5ntbamFWbE4WMNHI',
    appId: '1:606046467024:ios:73ff3d533225195d2a7fd5',
    messagingSenderId: '606046467024',
    projectId: 'ellemora-7629c',
    storageBucket: 'ellemora-7629c.appspot.com',
    iosBundleId: 'com.example.agiletask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc1OVJRns3lTpiMqr5ntbamFWbE4WMNHI',
    appId: '1:606046467024:ios:73ff3d533225195d2a7fd5',
    messagingSenderId: '606046467024',
    projectId: 'ellemora-7629c',
    storageBucket: 'ellemora-7629c.appspot.com',
    iosBundleId: 'com.example.agiletask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrPrjW0mu1TwvwNjeIz81-d90o299i8NA',
    appId: '1:606046467024:web:40521d7b1fdaae912a7fd5',
    messagingSenderId: '606046467024',
    projectId: 'ellemora-7629c',
    authDomain: 'ellemora-7629c.firebaseapp.com',
    storageBucket: 'ellemora-7629c.appspot.com',
    measurementId: 'G-Z2L47F4EQ8',
  );
}
